### ISSUE TITLE
Please throw exceptions when error occours

### ISSUE THREAD

**Issue by Arkanius** [convenia/graphql-client#10]
I'm trying to use *Billing SDK* and the first thing that I have to do is create a contact like: 
```php
try {
    $find = $this->billing->contact()->set([
        'name' => $contact['name'],
        'email' => $contact['email'],
        'telephone' => $contact['phone']
    ]);
    } catch (CompanyException $e) {
         throw new CompanyException("Billing Error: Could not create contact");
    };
```

As you can see, I tried to use exceptions but noone exception has been threw in this method. Just a json error return.

**Comment by tauanlemos** [comment]
Fixed in master. Now throwing a GraphQLException
